WebClient/Models/Article.cs
namespace WebClient.Models;

public class Article
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Slug { get; set; }
    public DateTime? CreatedOn { get; set; }
    public DateTime? PublicationDate { get; set; }
}

WebClient/Models/ErrorViewModel.cs
namespace WebClient.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WebClient/Models/TagDTO.cs
using FluentRepositories.Attributes;

namespace WebClient.Models;

[DefaultTable("Etiquetas")]
public class TagDTO
{
    [DatabaseColumn("Id")]
    public int Id { get; set; }

    [DatabaseColumn("Nombre")]
    public string Name { get; set; }
}

WebClient/Controllers/HomeController.cs
using AdvancedRepositories.Core.Repositories;
using AdvancedRepositories.Core.Repositories.Fluent;
using Microsoft.AspNetCore.Mvc;
using WebClient.Infrastructure;
using WebClient.Models;

namespace WebClient.Controllers;

public class HomeController : Controller
{
    IArticleRepository _articleRepository;
    IArticleTypedRepository _articleTypedRepository;
    FluentRepository _fluentRepo;

    public HomeController(IArticleRepository articleRepository, FluentRepository fluentRepository, IArticleTypedRepository articleTypedRepository)
    {
        _articleRepository = articleRepository;
        _fluentRepo = fluentRepository;
        _articleTypedRepository = articleTypedRepository;
    }

    [HttpGet]
    public IActionResult Index(int searchType = 1, string? title = null)
    {
        IndexVM vm = new IndexVM();
        
        vm.Title = title;
        vm.SearchType = searchType;

        DbResult<List<Article>> articleResult = searchType switch
        {
            1 => _articleRepository.FindClassic(title),
            2 => _articleRepository.FindAdvanced(x => x.ColumnName("Titulo").Like(title)),
            3 => _articleTypedRepository.FindAdvanced(x => x.ColumnName("Titulo").Like(title)),
            4 => _fluentRepo.Select<Article>()
                        .From("Articulos")
                        .Where(x => x.ColumnName("Titulo").Like(title))
                        .GetList(x =>
                        {
                            x.Add("Id", "Id");
                            x.Add("Title", "Titulo");
                            x.Add("Slug", "Slug");
                            x.Add("CreatedOn", "FechaCreacion");
                            x.Add("PublicationDate", "FechaPublicacion");
                        }),
            5 => _fluentRepo.Select<Article>("Id", "Titulo", "Slug", "FechaCreacion", "FechaPublicacion")
                        .From("Articulos")
                        .Where(x => x.ColumnName("Titulo").Like(title))
                        .GetList(x =>
                        {
                            x.ByColumnAttribute = true;
                            x.ByPropertyName = true;
                            x.MapPropertyToDbField = y =>
                            {
                                y.Add("Title", "Titulo");
                                y.Add("CreatedOn", "FechaCreacion");
                                y.Add("PublicationDate", "FechaPublicacion");
                            };
                        })
        };

        if(articleResult.IsSuccess)
            vm.Articles = articleResult.Value;

        return View(vm);
    }

    [HttpPost]
    public IActionResult Index(Article article)
    {
        DbResult result = null;
        bool insert = false;

        if(insert)
            result = _articleRepository.Insert(article);
        else
            result = _articleRepository.Update(article, 10);

        return RedirectToAction("Index");
    }
}

public class IndexVM
{
    public string Title { get; set; }
    public int SearchType { get; set; }
    public List<Article> Articles { get; set; } = new();
}

WebClient/Views/Home/Components/TagSelect/TagSelectViewComponent.cs
using AdvancedRepositories.Core.Repositories;
using AdvancedRepositories.Core.Repositories.Fluent;
using Microsoft.AspNetCore.Mvc;
using WebClient.Models;

namespace WebClient.Views.Home.Components.TagSelect;

public class TagSelectViewComponent : ViewComponent
{
    FluentRepository _fluentRepository;
	public TagSelectViewComponent(FluentRepository fluentRepository)
	{
		_fluentRepository= fluentRepository;
	}

    public async Task<IViewComponentResult> InvokeAsync()
    {
        DbResult<List<TagDTO>> result = _fluentRepository.AutoList<TagDTO>();

        if (result.IsFailure) return View(new List<TagDTO>());

        return View(result.Value);
    }
}

WebClient/Views/Home/Components/TagSelect/Default.cshtml
@model List<TagDTO>
<div class="mb-3 px-3">
    <label class="form-label">Tag</label>
    <select class="form-select" name="Tag">
                <option selected>-- Select --</option>
    @foreach (TagDTO tag in Model)
    {
        <option value="@tag.Id">@tag.Name</option>
    }
    </select>
</div>

WebClient/Views/Home/Index.cshtml
@using WebClient.Controllers;
@model IndexVM
@{
    ViewData["Title"] = "Home Page";
}

<form asp-controller="Home" asp-action="Index" method="get" class="card">
    <a class="card-header text-decoration-none" data-bs-toggle="collapse" href="#searchArticle" role="button">
        <h3>Search</h3>
    </a>

    <div class="card-body p-0" id="searchArticle">
        <div class="mb-3 px-3 pt-3">
            <label class="form-label">Title</label>
            <input class="form-control" name="title" value="@Model.Title">
        </div>
        
        <div class="mb-3 p-3">
            <select class="form-select" name="searchType">
                <option value="1" selected="@(Model.SearchType == 1)">Classic</option>
                <option value="2" selected="@(Model.SearchType == 2)">Advanced</option>
                <option value="3" selected="@(Model.SearchType == 3)">Typed Advanced</option>
                <option value="4" selected="@(Model.SearchType == 4)">Explicit Fluent</option>
                <option value="5" selected="@(Model.SearchType == 5)">Fluent with fallback </option>
            </select>
        </div>

        <div class="card-footer text-end">
            <button type="submit" class="btn btn-primary">SEARCH</button>
        </div>
    </div>
</form>

<form asp-controller="Home" asp-action="Index" method="post" class="card mt-3">
    <a class="card-header text-decoration-none" data-bs-toggle="collapse" href="#addArticle" role="button">
        <h3>Add new article</h3>
    </a>

    <div class="card-body p-0 collapse" id="addArticle">
        <div class="mb-3 px-3 pt-3">
            <label class="form-label">Title</label>
            <input class="form-control" name="Title">
        </div>
        
        <vc:tag-select></vc:tag-select>

        <div class="card-footer text-end">
            <button type="submit" class="btn btn-primary">INSERT</button>
        </div>
    </div>
</form>


<h2 class="text-center py-5">Articles found (@Model.Articles.Count)</h2>


<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Slug</th>
            <th>CreatedOn</th>
            <th>PublicationDate</th>
        </tr>
    </thead>
    <tbody>
        @foreach(Article article in Model.Articles)
        {
            <tr>
                <td>@article.Id</td>
                <td>@article.Title</td>
                <td>@article.Slug</td>
                <td>@article.CreatedOn</td>
                <td>@article.PublicationDate</td>
            </tr>
        }
    </tbody>
</table>

WebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebClient.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebClient</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>